refactor "store.go"
LedgerHQ/bitcoin-keychain pull request #24
Opened 2021-06-08 16:05 UTC by CedricCabessa

remove duplication
The real code is moved to function in store.go
memory.go and redis.go do the access layer thing and call those functions

2021-06-08 16:06 UTC, CedricCabessa commented on pkg/keystore/redis.go
> +		if err := set(s.db, id.String(), meta); err != nil {
totally not sure here
We are overwritting the same key again? It was present in the original code, but in a different form

2021-06-08 16:08 UTC, CedricCabessa commented
noob go question: go.mod and go.sum have changed locally.
Why? is it mage or the go compiler? I didn't ask for anything :-)
What I am supposed to do with that?

2021-06-08 16:21 UTC, CedricCabessa commented
diff is hard to read :-(
Of course feel free to be mega pedantic on all the thing that are not "go friendly", my first go PR :baby_bottle: 

I went with function, don't sure if there is a better way?
Like sometime I need to give the store as [first parameter](https://github.com/LedgerHQ/bitcoin-keychain/pull/24/files#diff-31a59120b1111834534964583197e5db8672d79895943696e69cb9518fdc57c7R436) it feel a bit weird.
Without inheritance can we do better? :thinking:

2021-06-09 12:00 UTC, onyb requested changes

2021-06-09 14:23 UTC, CedricCabessa commented on pkg/keystore/memory.go
> +	keystoreReset(meta)
no, overkill

2021-06-09 14:27 UTC, CedricCabessa commented
(those 2 commit can be squashed)

2021-06-11 06:46 UTC, onyb approved these changes
Can you please fix the errors reported by `mage -v lint`? Looks good overall! Congrats on your first Go PR.

2021-06-11 06:46 UTC, onyb commented on pkg/keystore/store.go
> +func (meta *Meta) keystoreGetAddressesPublicKeys(derivations []DerivationPath) ([]string, error) {
Nit: can you please make sure you use `m` everywhere to follow the Go convention?

2021-06-11 06:46 UTC, onyb commented on pkg/keystore/store.go
> +	id uuid.UUID,
Unused? Also, check the other functions.

2021-06-11 07:37 UTC, merged