Vg 521 wd backend
LedgerHQ/bitcoin-keychain pull request #26
Opened 2021-06-24 09:33 UTC by CedricCabessa

Draft for WD backend
See commits message for more information

2021-06-25 06:55 UTC, onyb commented on pb/keychain/service.proto
> +  uint32 index = 6;
Let's call this `account_index`.

Also for future, we may want to stop having the account index in `FromChainCode` message. Let's not do it now, else it'll break the current Lama code.

2021-06-25 07:29 UTC, onyb requested changes

2021-06-25 07:29 UTC, onyb commented on pb/keychain/service.proto
> +  string info = 7;
Please add some comments about this field, and what it's useful for. Also, let's specify the schema expected by this field for the known use-cases we have. Remember that this file is the only source of information for external teams.

Also, what do you think of `metadata` as a name? It indicates that it is a non-essential field.

2021-06-25 07:29 UTC, onyb commented on pkg/keystore/wd.go
> +}
```suggestion
type WDKeystore struct {
	baseRedisKeystore
}

func NewWDKeystore(redisOpts *redis.Options) (*WDKeystore, error) {
	rdb := redis.NewClient(redisOpts)

	if _, err := rdb.Ping(context.Background()).Result(); err != nil {
		return nil, fmt.Errorf("Pinging redis failed: %w", err)
	}

	baseKeystore := baseRedisKeystore{
		db:     rdb,
		client: bitcoin.NewBitcoinClient(),
	}

	return &WDKeystore{baseKeystore }, nil
}
```

Then you should be able to add the following to `redis_common.go`.

```go
type baseRedisKeystore struct {
	db     *redis.Client
	client bitcoin.CoinServiceClient
}

func (s *baseRedisKeystore) Get(id uuid.UUID) (KeychainInfo, error) {
	var meta Meta

	err := get(s.db, id.String(), &meta)
	if err != nil {
		return KeychainInfo{}, ErrKeychainNotFound
	}

	return meta.Main, nil
}
```

The `client` and `db` fields on `WDKeystore` will work as usual.

This pattern gives you the benefits of inheritance but using composition. You can read about it [here](https://travix.io/type-embedding-in-go-ba40dd4264df).

2021-06-25 09:41 UTC, CedricCabessa commented on pkg/keystore/wd.go
> +}
very cool, thx !

2021-06-25 09:43 UTC, CedricCabessa commented on pb/keychain/service.proto
> +  uint32 index = 6;
>  Let's not do it now, else it'll break the current Lama code.

What do you want me to do :sweat_smile: ?
I've discussed with Edouard, he is ok to pass the index. Also this information is mandatory to speak "wd"
Are you saying to remove "account_index" later on?

2021-06-25 09:44 UTC, CedricCabessa commented
I'll squash the commit before merge

2021-06-28 13:56 UTC, onyb commented on pb/keychain/service.proto
> +  uint32 index = 6;
I was saying that `FromChainCode` also has the `account_index` which is duplication. If we pass it in `CreateKeychainRequest`, then we don't need to provide it in `FromChainCode`.

2021-06-29 06:53 UTC, onyb approved these changes

2021-06-29 06:55 UTC, merged